load(
    "//markdown/toolchains/lint/known_toolchain_instances/compiled:defs.bzl",
    "make_default_markdown_lint_toolchain_for_platform"
)

make_default_markdown_lint_toolchain_for_platform(platform_os = "@platforms//os:linux")